name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install

      - name: Build project (if necessary)
        if: ${{ fileExists('package.json') && contains(steps, '"build"') }}
        run: npm run build

      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{ "clearCache": true }' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
